config/routes.rb
TomatoBag::Application.routes.draw do
  scope defaults: (Rails.env.production? ? { protocol: 'https' } : {}) do
    devise_for :users
  end

  root to: "dvds#new_releases"

  resources :dvds do
    collection do
      get 'new_releases'
      get 'upcoming_releases'
      get 'top_ten_new_releases'
      get 'top_ten_upcoming_releases'
    end
  end

  resources :movies do
    collection do
      get 'search'
    end
  end

  resources :flagged_movies, only: [:create, :destroy, :update] do
    collection do
      get 'wanted'
      get 'watched'
    end
  end

  

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_filter :load_wanted_movie_ids

  def show
    @movie = Movie.find(params[:id])
  end

  def search
    if params[:q].present?
      @movies = Movie.search(params[:q])
    else
      @movies = []
    end
  end
end

app/views/movies/_movie.html.haml
%li
  .movie-poster
    %h6.subheader= movie.title
    %a.th.radius{'href' => movie_path(movie.id)}
      =image_tag movie.posters.detailed
    .movie-controls
      - if wanted_movie_ids.include?(movie.id.to_i)
        %i.fi-check>
        =" Wanted"
      - else
        = link_to 'Bag!', flagged_movies_path(movie_id: movie.id), method: :post, class: 'small button success'
      = freshness(movie)

app/views/movies/search.html.haml
%h2 Search Movies

= form_tag search_movies_path, method: :get do
  = text_field_tag :q, params[:q]
  = submit_tag 'Search', class: 'button'

%ul.small-block-grid-2.large-block-grid-4
  - @movies.each do |movie|
    = render 'movie', movie: movie, wanted_movie_ids: @wanted_movie_ids

app/views/movies/show.html.haml
%h2= @movie.title
%h4.subheader= dvd_availability(@movie.release_dates.dvd)
- if user_signed_in? && !current_user.wanted_movie?(@movie)
  = form_tag flagged_movies_path, method: :post do |f|
    = hidden_field_tag :movie_id, @movie.id
    = submit_tag 'Add to Wanted', class: 'small button success'
- elsif user_signed_in?
  = form_tag flagged_movie_path(@movie.id), method: :delete do |f|
    = hidden_field_tag :movie_id, @movie.id
    = hidden_field_tag :state, 'watched'
    = submit_tag 'Remove from wanted', class: 'small button secondary'
.row
  .large-4.columns
    = image_tag @movie.posters.original, class: 'th radius movie-poster'
  .large-8.columns
    %h4.subheader Synopsis
    %p= @movie.synopsis
    = freshness(@movie)
.row
  .large-4.large-offset-8.columns
    - @movie.similar_movies.each do |movie|
      = render 'movies/movie', movie: movie, wanted_movie_ids: @wanted_movie_ids