config/routes.rb
TomatoBag::Application.routes.draw do
  scope defaults: (Rails.env.production? ? { protocol: 'https' } : {}) do
    devise_for :users
  end

  root to: "dvds#new_releases"

  resources :dvds do
    collection do
      get 'new_releases'
      get 'upcoming_releases'
      get 'top_ten_new_releases'
      get 'top_ten_upcoming_releases'
    end
  end

  resources :movies do
    collection do
      get 'search'
    end
  end

  resources :flagged_movies, only: [:create, :destroy, :update] do
    collection do
      get 'wanted'
      get 'watched'
    end
  end

  

end

app/controllers/flagged_movies_controller.rb
class FlaggedMoviesController < ApplicationController
  before_filter :authenticate_user!

  def wanted
    @wanted_movies = current_user.flagged_movies.wanted
  end

  def watched
    @watched_movies = current_user.flagged_movies.watched
  end

  def create
    params[:state] ||= 'wanted'
    movie = Movie.find(params[:movie_id])
    @flagged_movie = current_user.flagged_movies.build(state: params[:state], rt_movie_id: movie.id,
                                      rt_imdb_id: movie.imbd_id, poster_detailed_url: movie.poster,
                                      poster_original_url: movie.poster_large, title: movie.title)
    if @flagged_movie.save
      flash[:notice] = "#{movie.title} successfully added to your wanted list"
      redirect_back_or_default root_url
    else
      redirect_to root_url, :notice => "There was a problem adding that movie"
    end
  end

  # this is a pretty weird update action since it's only being used to
  # change the state column of a flagged_movie
  def update
    @flagged_movie = current_user.flagged_movies.find(params[:id])
    new_state = params[:flagged_movie][:state]
    if @flagged_movie.update_attributes(state: params[:flagged_movie][:state])
      respond_to do |format|
        format.html do
          flash[:notice] = "#{@flagged_movie.title} was moved to your #{new_state} list"
          redirect_back_or_default root_url
        end
        format.js   { flash.now[:notice] = "#{@flagged_movie.title} was moved to your #{new_state} list" }
      end
    end
  end

  def destroy
    if params[:movie_id].present?
      @flagged_movie = current_user.flagged_movies.where(rt_movie_id: params[:movie_id]).first
    else
      @flagged_movie = current_user.flagged_movies.find(params[:id])
    end
    if @flagged_movie.destroy
      respond_to do |format|
        format.html do
          flash[:notice] = "Movie removed from your wanted list"
          redirect_back_or_default root_url
        end
        format.js { flash.now[:notice] = "#{@flagged_movie.title} removed from your wanted list" }
      end
    end
  end

  private

  def flagged_movie_params
    params.require(:flagged_movie).permit(:state)
  end
end

app/views/flagged_movies/_flagged_movie.html.haml
.row
  .movie-item.large-12.columns{id: "flagged_movie_#{flagged_movie.id}"}
    .row
      .large-2.columns
        = image_tag flagged_movie.poster_detailed_url
      .large-10.columns
        .row
          .large-8.columns.movie-title
            %h4.subheader= flagged_movie.title
          .large-2.columns.freshness
            = freshness(flagged_movie.movie)
      .large-10.columns
        %p.small= flagged_movie.movie.synopsis
    .row
      .large-4.large-offset-8.columns
        = link_to 'Remove', flagged_movie, remote: true, method: :delete, class: 'button small'
        - if !flagged_movie.watched?
          = link_to 'Mark as Watched', flagged_movie_path(id: flagged_movie.id, 'flagged_movie[state]' => 'watched'),  remote: true, method: :put, class: 'button small'
        - elsif flagged_movie.watched?
          = link_to 'Unmark as Watched', flagged_movie_path(id: flagged_movie.id, 'flagged_movie[state]' => 'wanted'),  remote: true, method: :put, class: 'button small'

app/views/flagged_movies/destroy.js.erb
$("#flash_notice").html("<%= escape_javascript(flash.now[:notice])%>");
$("#flash_notice").show(300);
$("#flash_notice").fadeOut(5000);
$("#flagged_movie_<%= @flagged_movie.id %>").fadeOut(300);

app/views/flagged_movies/update.js.erb
$("#flash_notice").html("<%= escape_javascript(flash.now[:notice])%>");
$("#flash_notice").show(300);
$("#flash_notice").fadeOut(5000);
$("#flagged_movie_<%= @flagged_movie.id %>").fadeOut(300);

app/views/flagged_movies/wanted.html.haml
%h2 My Wanted Movies
- if @wanted_movies.empty?
  %p You don't have any movies saved to your wanted list.  Check out the #{link_to 'New Releases', new_releases_dvds_path} and add some!
= render @wanted_movies

app/views/flagged_movies/watched.html.haml
%h2 My Watched Movies
- if @watched_movies.empty?
  %p You haven't flagged any movies as being watched.  Check out your #{link_to 'Wanted Movies', wanted_flagged_movies_path} and watch some!
= render @watched_movies