config/routes.rb
TomatoBag::Application.routes.draw do
  scope defaults: (Rails.env.production? ? { protocol: 'https' } : {}) do
    devise_for :users
  end

  root to: "dvds#new_releases"

  resources :dvds do
    collection do
      get 'new_releases'
      get 'upcoming_releases'
      get 'top_ten_new_releases'
      get 'top_ten_upcoming_releases'
    end
  end

  resources :movies do
    collection do
      get 'search'
    end
  end

  resources :flagged_movies, only: [:create, :destroy, :update] do
    collection do
      get 'wanted'
      get 'watched'
    end
  end

  

end

app/views/layouts/_navbar.html.haml
%nav.top-bar
  %ul.title-area
    %li.name
      %h1
        =link_to 'TomatoBag', root_url
  %section.top-bar-section
    %ul.right
      %li= link_to 'Search', search_movies_url
      %li.divider.hide-for-small
      %li= link_to 'Available Now', new_releases_dvds_url
      %li.divider.hide-for-small
      %li= link_to 'Available Soon', upcoming_releases_dvds_url
      %li.divider.hide-for-small
      %li.has-dropdown.not-click
        %a{href: '#'} Top Tens
        %ul.dropdown
          %li= link_to 'New DVD releases', top_ten_new_releases_dvds_path
          %li= link_to 'Upcoming DVD releases',top_ten_upcoming_releases_dvds_path
      - if user_signed_in?
        %li.divider.hide-for-small
        %li.has-dropdown.not-click
          %a{href: '#'} My Movies
          %ul.dropdown
            %li= link_to 'Wanted Movies', wanted_flagged_movies_path
            %li= link_to 'Watched Movies', watched_flagged_movies_path
      - if user_signed_in?
        %li.divider.hide-for-small
        %li= link_to 'Sign Out', destroy_user_session_url, method: :delete
      - else
        %li.divider.hide-for-small
        %li= link_to 'Sign In', new_user_session_url

app/views/layouts/application.html.haml
!!!
/ paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/
/[if lt IE 7 ] <html class="ie6" lang="en">
/[if IE 7 ] <html class="ie7" lang="en">
/[if IE 8 ] <html class="ie8" lang="en">
/ [if (gte IE 9)|!(IE)]><!
%html{:lang => "en"}
  / <![endif]
  %head
    %meta{:charset => "utf-8"}/
    / Uncomment to make IE8 render like IE7
    / <meta http-equiv="X-UA-Compatible" content="IE=7" />
    / Set the viewport width to device width for mobile
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "TomatoBag"
    = stylesheet_link_tag    "application"
    = javascript_include_tag "vendor/custom.modernizr"
    = csrf_meta_tags
  %body
    = render 'layouts/navbar'
    .row
      = render 'shared/notices'
      = yield
    = javascript_include_tag "application"